### ISSUE TITLE
Duplicates in the ref dataset

### ISSUE THREAD

**Issue by nlehuby** [mapsme/osm_conflate#10]
Sometimes, the dataset can contain duplicates.
It could be great to have a field in the profile, to specify that many elements could match the same OSM object.

**Comment by Zverik** [comment]
And what should be done in this case?

**Comment by nlehuby** [comment]
Only keep one item fom the ref dataset.

If you perform the validation of each item separatly, you won't even notice the duplicate, and end up creating multiple items that represent the same location
