### ISSUE TITLE
multiple keys in query

### ISSUE THREAD

**Issue by cascafico** [mapsme/osm_conflate#14]
Having mixed fuel stations types (amenity=fuel, wateray=fuel, disused|abandoned:amenity=fuel) how should I write profile query ?
Otherwise, since I've no programming skills, it is possible passing an overpass-turbo generated osm instead?

**Comment by Zverik** [comment]
Hi, good question — I [implemented that](https://github.com/mapsme/osm_conflate/blob/master/CHANGELOG.md#130) recently, but didn't take time to document it.

You would need something like this:
```python
query = [[('amenity', 'fuel')], [('waterway', 'fuel')]]
```

Also, lifecycle prefixes (`disused:`, `abandoned:` etc.) are conflated automatically. That is, if you have `amenity=fuel` in your data, and the corresponding object in OSM has `disused:amenity=fuel`, then these two objects would be matched.

You of course can pass a prepared osm file with `--osm` command line argument. For overpass turbo, it is recommended to use `[out:xml]` and `out meta center`.
