### ISSUE TITLE
Audit "move"

### ISSUE THREAD

**Issue by cascafico** [mapsme/osm_conflate#15]
Maybe it is not an issue, but something I don't understand:

On a project element (ie: [ref 3984](http://audit.osmz.ru/run/IFS/3984) I see three choices: 
- Good
- Don't change
- Skip

In [audit JSON](https://wiki.openstreetmap.org/wiki/OSM_Conflator#Audit_JSON) also "Move" is listed. When should it appear in webGUI?

**Comment by Zverik** [comment]
When the marker is green, you can move it in the GUI to a better location.
