### ISSUE TITLE
Multiple validations

### ISSUE THREAD

**Issue by cascafico** [mapsme/osm_conflate#16]
When validating approx 20k nodes Italy Fuel Stations, I hit some POI I already validated (with a fixme value). I guess nodes are randomly selected.

Would be better complete nodes never validated before starting with double check?

**Comment by Zverik** [comment]
Good idea, I had the same one while validating a project with only 8 non-validated points, and never getting these.

**Comment by cascafico** [comment]
Another question related to multiple validations.

When I find a POI already validated with a fixme value (ie: "wrong name"), what happens if I click "Good"? Will the fixme be kept or should I touch it to get "Record changes" button?

**Comment by Zverik** [comment]
"Fixme" are kept when you click good, as well as other changes.

If a point has a "rejected" verdict, you have to click "Don't Change" to keep the verdict.

**Comment by Zverik** [comment]
Fixed in https://github.com/mapsme/cf_audit/commit/25a8a285f2591d86b292262695e27df050c5257d
