### ISSUE TITLE
no polygons in output

### ISSUE THREAD

**Issue by cascafico** [mapsme/osm_conflate#19]
After running conflator

`$ conflate -i tmp/short_anagrafica-2018-09-13-csv.json -v  --changes osmchanges/changes.json --osm query_s-Cfr.osm -o osm/result.osm -c preview/preview.json profile-mise.py
`

I've uploaded preview.json file in audit tool [project IFGS](http://audit.osmz.ru/project/IGFS/) and I can validate nodes and polygons. 
If I load in JOSM  [result.osm](https://github.com/cascafico/OSM-ItalyFuelStations/blob/master/osm/result.osm), it seems the file doesn't have polygons (way tags), buy just nodes and relations.
Where am I wrong?.

**Comment by Zverik** [comment]
It has polygons, but not their referred nodes. So they are present, but not displayed. If you press "upload", you'll see their count.

**Comment by cascafico** [comment]
> It has polygons, but not their referred nodes. So they are present, but not displayed. If you press "upload", you'll see their count.

Is there a workaround to allow post-conflation selecting/editing on polygons? I was trying to use the "upload selected" JOSM funcion, but I cannot select them.

PS: thank for your ultra-fast reply :-)

**Comment by Zverik** [comment]
I don't know for sure, but try "File → Update Data", it worked for me on your file.
