### ISSUE TITLE
Keep track of OSM data with no third-party dataset

### ISSUE THREAD

**Issue by Janjko** [mapsme/osm_conflate#20]
I think we need a way to keep track of data on OSM that has no third-party datasets. That way, historic OSM data is the authoritative dataset that needs to be conflated with current OSM data. If there is a change in current OSM data, we can either change (revert) the OSM database, or import the current OSM to act as new authoritative data.

I'm somewhat new to OSM Conflator,  so I'm not sure if this function already exist. We would need to have an initial download from overpass using the `query` variable from the `profile.py`. The data would be converted into the input json.

Does this agree with your concept of this tool?

**Comment by Zverik** [comment]
Well if you download some data then it makes the data third-party for this tool. So yes, you can get an old OSM extract, write a profile to convert it to a data source, and conflate it with the recent OSM data, checking for changes. Not that I approve of a practice of keeping authoritative data in OSM, but it is possible I guess.

**Comment by Janjko** [comment]
Not so much authoritative, maybe that was poor wording. It's more like keeping an eye on the data. Thanks for the answer.
